name: CI/CD StockFlow

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:

  testes:
    name: Testes Unitários
    runs-on: ubuntu-latest

    steps:
      - name: Baixar código do repositório
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Executar testes unitários
        run: node --test tests/produtos.test.js


  docker:
    name: Build e Push Docker
    runs-on: ubuntu-latest
    needs: testes

    if: github.event_name == 'push' && github.ref == 'refs/heads/main'

    steps:
      - name: Baixar código do repositório
        uses: actions/checkout@v4

      - name: Login no Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Criar imagem Docker
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./backend/Dockerfile
          push: true
          tags: yuritwardowski/stockflow:latest