name: CI/CD StockFlow

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  testes:
    name: Testes Unitários
    runs-on: ubuntu-latest

    steps:
      - name: Baixar código do repositório
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Executar testes unitários
        run: node --test tests/produtos.test.js